services:
  frontend:
    build:
      context: ./apps/frontend
      target: dev
    ports:
      - "8100:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/backend
      target: dev
    ports:
      - "8101:3001"
    volumes:
      - ./apps/backend/src:/app/src
      - ./data:/app/data
      - E:/media/tv:/tv:ro
      - E:/media/movies:/movies:ro
      - E:/media/books:/books:ro
      # Optional: in the scenario that you are not doing books/{ebooks,audiobooks} together.
      # - E:/media/ebooks:/ebooks:ro
      # - E:/media/audiobooks:/audiobooks:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      # Optional: in the scenario that you are not doing books/{ebooks,audiobooks} together.
      # - EBOOKS_PATH=/ebooks
      # - AUDIOBOOKS_PATH=/audiobooks

volumes:
  data:
